/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.Loader.setConfig({
    enabled: true
});

Ext.application({
    models: [
        'Expense',
        'Employee'
    ],
    stores: [
        'MenuStore',
        'ExpenseStore',
        'EmployeeStore'
    ],
    views: [
        'Viewport',
        'Info',
        'Menu',
        'DomesticExpense',
        'AbroadExpense',
        'Page',
        'Sign',
        'AddExpenseContainer',
        'OverviewList',
        'Overview',
        'ExpenseDetail'
    ],
    name: 'Expense',
    controllers: [
        'MenuController',
        'ExpenseController'
    ],

    launch: function() {

        Ext.create('Expense.view.Viewport', {fullscreen: true});
    }

});
