/*
 * File: app/controller/ExpenseController.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Expense.controller.ExpenseController', {
    extend: 'Ext.app.Controller',
    alias: 'controller.expensecontroller',

    config: {
        refs: {
            nav: 'overview'
        },

        control: {
            "#overviewlist": {
                disclose: 'showDetailExpense'
            },
            "#totaloverviewlist": {
            	disclose: 'showExpensePDF'
            }
        }
    },

    showDetailExpense: function(list, record, target, index, e, options) {
    	if(record.getData()['expenseLocation'] == 'Abroad'){
	        this.getNav().push({
	            xtype: 'abroadexpensedetail',
	            record: record
	        });
    	} else {
    		this.getNav().push({
	            xtype: 'domesticexpensedetail',
	            record: record
	        });
    	}
    },
    
    showExpensePDF: function(list, record, target, index, e, options) {
    	if(Ext.device.Connection.isOnline()){
		 Ext.Viewport.setActiveItem(Ext.create('Ext.ux.panel.PDF',{
	            fullscreen: true,
	            layout    : 'fit',
	            src       : Expense.app.getBaseURL() + '/resources/expenseService/getExpenseFormPDF', // URL to the PDF - Same Domain or Server with CORS Support
	            extraParams: 'token='+Expense.app.getToken()+'&expenseFormId='+Ext.getStore('expensestore').getTotalCount() //TODO expenseFormId
	        }));
    	}
    }

});