/*
 * File: app/controller/LoginController.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Expense.controller.LoginController', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            login: 'loginpanel'
        },

        control: {
            "#login": {
                tap: 'onButtonTap'
            }	
        }
    },

    onButtonTap: function(button, e, options) {
        var fields= this.getLogin().getValues();  
        Ext.Ajax.request({
			url : 'http://localhost:8888/resources/userService/login',
			method : 'POST',
			useDefaultXhrHeader: false, //http://stackoverflow.com/questions/10830334/ext-ajax-request-sending-options-request-cross-domain-when-jquery-ajax-sends-get
			params: {
                email: fields.email,
                password: fields.password
            },
			callback : function(options, success, response) {
				console.log("callback LOGIN");
				console.log(response.responseText);
				Expense.app.token = response.responseText;
				Ext.Viewport.setActiveItem(Ext.getCmp('viewport'));
				var store = Ext.getStore('employeestore');
				var formPanel = Ext.getCmp('infopanel'); //TODO niet met id's werken! 
				Ext.Ajax.request({
							url : 'http://localhost:8888/resources/userService/getEmployee',
							method : 'POST',
							useDefaultXhrHeader : false, // http://stackoverflow.com/questions/10830334/ext-ajax-request-sending-options-request-cross-domain-when-jquery-ajax-sends-get
							params : {
								token : Expense.app.token
							},
							callback : function(options, success,response) {
								store.setData(response.responseText);
								console.log(store.getCount());
								var employee = store.getAt(0);
								formPanel.setRecord(employee);
							}
				});
			}
		});

    }

});