/*
 * File: app/controller/LoginController.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Expense.controller.LoginController', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            login: 'loginpanel'
        },

        control: {
            "#login": {
                tap: 'onButtonTap'
            }
        }
    },

    onButtonTap: function(button, e, options) {

        //display Loading indicator to user
        //mainPanel.setLoading(true, false);

        Ext.Ajax.request({
            url: 'http://kulcapexpenseapp.appspot.com/resources/userService/login',
            method: 'post',
            params: {
                UserName: this.getLogin().email,
                Password: this.getLogin().password
                //, RememberMe: Ext.getCmp(‘RememberMe’).isChecked()},
                //failure : function(response){
                //data = Ext.decode(response.responseText);
                //Ext.Msg.alert(‘Login Error’, data.errorMessage, Ext.emptyFn);
            }
            /*,
            success: function(response, opts) {
            data = Ext.decode(response.responseText);
            if (data.errorMessage != null)
            {
            Ext.Msg.alert(‘Login Error’, data.errorMessage, Ext.emptyFn);
            mainPanel.setLoading(false);
            } else {
            //hide the Loading mask
            mainPanel.setLoading(false);
            //show the next screen
            mainPanel.setActiveItem(dashboard, ‘slide’);
        }*/
    });

    }

});