/*
 * File: app/controller/MyInfoController.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Expense.controller.MyInfoController',{
	extend : 'Ext.app.Controller',
	
	config : {
		refs : {
			myinfo : 'infopanel'
		},
		control : {
			"formpanel" : {
				show : 'onFormpanelInitialize' //TODO oproepen op juiste moment,  nu in callback van login
			}
		}
	},
	
	onFormpanelInitialize : function(component, options) {
		var store = Ext.getStore('employeestore');
		var formPanel = this.getMyinfo();
		if (Expense.app.token != '') {
			Ext.Ajax.request({
						url : 'http://localhost:8888/resources/userService/getEmployee',
						method : 'POST',
						useDefaultXhrHeader : false, // http://stackoverflow.com/questions/10830334/ext-ajax-request-sending-options-request-cross-domain-when-jquery-ajax-sends-get
						params : {
							token : Expense.app.token
						},
						callback : function(options, success,response) {
							console.log("callback myINFO onFormPanelInitialize");
							store.setData(response.responseText);
							console.log(store.getCount());
							var employee = store.getAt(0);
							formPanel.setRecord(employee);
						}
					});
		}
	}
});