/*
 * File: app/controller/MyInfoController.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Expense.controller.MyInfoController', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            myinfo: 'infofield'
        },

        control: {
            "#infofield": {
                initialize: 'onFieldsetInitialize'
            }
        }
    },

    onFieldsetInitialize: function(component, options) {
        var store = Ext.create('Expense.store.EmployeeStore',
            {
                autoLoad: true,
                model: 'Expense.model.Employee',
                storeId: 'employeestore',
                proxy: {
                    type: 'ajax',
                    url: 'employee.json',
                    reader: {
                        type: 'json'
                    }
                }
            });
        var employee = store.getData()[0];
        console.log(employee);
        //this.getMyinfo().setRecord(
    }

});