/*
 * File: app/view/Info.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Expense.view.Info', {
    extend: 'Ext.Container',
    alias: 'widget.info',

    config: {
        items: [
            {
                xtype: 'fieldset',
                id: 'infofield',
                title: '1. Your info',
                items: [
                    {
                        xtype: 'selectfield',
                        label: 'Month'
                    },
                    {
                        xtype: 'selectfield',
                        label: 'Year'
                    },
                    {
                        xtype: 'textfield',
                        id: 'firstName',
                        label: 'First Name',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        id: 'lastName',
                        label: 'Last Name',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        id: 'employeeNumber',
                        label: 'Employee Number'
                    },
                    {
                        xtype: 'selectfield',
                        id: 'unit',
                        label: 'Unit'
                    },
                    {
                        xtype: 'emailfield',
                        id: 'email',
                        label: 'Email',
                        placeHolder: 'email@example.com'
                    }
                ]
            }
        ]
    }

});