/*
 * File: app/view/InfoPanel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Expense.view.InfoPanel', {
    extend: 'Ext.form.Panel',
    alias: 'widget.infopanel',

    config: {
    	id: 'infopanel',
        items: [
            {
                xtype: 'fieldset',
                id: 'infofield',
                title: '1. Your info',
                items: [
                    {
                        xtype: 'selectfield',
                        label: 'Month',
                        name: 'month'
                    },
                    {
                        xtype: 'selectfield',
                        label: 'Year',
                        name: 'year'
                    },
                    {
                        xtype: 'textfield',
                        id: 'firstName',
                        label: 'First Name',
                        name: 'firstName',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        id: 'lastName',
                        label: 'Last Name',
                        name: 'lastName',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        id: 'employeeNumber',
                        label: 'Employee Number',
                        name: 'employeeNumber'
                    },
                    {
                        xtype: 'selectfield',
                        id: 'unit',
                        label: 'Unit',
                        name: 'unitId'
                    },
                    {
                        xtype: 'emailfield',
                        id: 'email',
                        label: 'Email',
                        name: 'email',
                        placeHolder: 'email@example.com'
                    }
                ]
            }
        ]
    }

});