/*
 * File: app/view/LoginPanel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Expense.view.LoginPanel', {
    extend: 'Ext.form.Panel',
    alias: 'widget.loginpanel',

    config: {
        height: 754,
        id: 'loginpanel',
        width: '100%',
        standardSubmit: true,
        url: 'http://localhost:8888/resources/userService/login',
        items: [
            {
                xtype: 'emailfield',
                id: 'email',
                label: 'Email',
                name: 'email',
                value: 'tim.ameye@student.kuleuven.be',
                placeHolder: 'email@example.com'
            },
            {
                xtype: 'passwordfield',
                id: 'password',
                label: 'Password',
                name: 'password',
                value: 'test123'
            },
            {
                xtype: 'button',
                height: 46,
                id: 'login',
                ui: 'action-round',
                width: 212,
                iconAlign: 'center',
                text: 'Login',
                action: 'login'
            }
        ]
    }

});