/*
 * File: app/view/LoginPanel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Expense.view.LoginPanel', {
    extend: 'Ext.form.Panel',
    alias: 'widget.loginpanel',

    config: {
        height: 754,
        id: 'loginpanel',
        width: 1017,
        items: [
            {
                xtype: 'emailfield',
                label: 'Email',
                value: 'tim.ameye@student.kuleuven.be',
                placeHolder: 'email@example.com'
            },
            {
                xtype: 'passwordfield',
                label: 'Password',
                value: 'test123'
            },
            {
                xtype: 'button',
                handler: function(button, event) {
                    var form = Ext.getCmp('loginpanel');
                    form.submit({
                        url: 'http://localhost:8888/resources/userService/login',
                        method: 'POST',
                        params: {
                            email: 'tim.ameye@student.kuleuven.be',
                            password: 'test123'
                        },
                        success: function (frm, res)  {
                            alert('Form submitted: ' + res);
                        },
                        failure: function (frm, res) {
                            alert('Form no submit!');
                        }
                    });



                },
                height: 46,
                id: 'login',
                ui: 'action-round',
                width: 212,
                iconAlign: 'center',
                text: 'Login'
            }
        ]
    }

});