/*
 * File: app/view/Overview.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Expense.view.Overview', {
    extend: 'Ext.navigation.View',
    alias: 'widget.overview',

    requires: [
        'Expense.view.OverviewList'
    ],

    config: {
        items: [
            {
                xtype: 'overviewlist'
            },{
	           	 xtype: 'toolbar',
	             docked: 'bottom',
	             id: 'toolbar',
	             items: [
	                 {
	                     xtype: 'button',
	                     docked: 'left',
	                     ui: 'action',
	                     iconCls: 'add',
	                     iconMask: true,
	                     text: 'Add Expense',
	                     action: 'addExpense'
	                 },{
	                	 xtype: 'button',
	                	 docked: 'right',
	                	 ui: 'action',
	                	 iconCls: 'arrow_right',
	                	 iconAlign: 'right',
	                	 iconMask: true,
	                	 text: 'Sign & Send',
	                	 action: 'sign'
	                 }
	             ]
            }
        ]
    }

});