/*
 * File: app/view/OverviewList.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Expense.view.OverviewList', {
    extend: 'Ext.dataview.List',
    alias: 'widget.overviewlist',

    config: {
        height: 770,
        id: 'overviewlist',
        ui: 'round',
        store: 'expensestore',
        onItemDisclosure: true,
        itemTpl: [
            '<div>{date:date("d/m/Y")} &mdash; <small>Description({amount}   {currency})</small></div>'
        ]
    }

});