/*
 * File: app/view/Page.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Expense.view.Page', {
    extend: 'Ext.Container',
    alias: 'widget.page',

    requires: [
        'Expense.view.Info',
        'Expense.view.Overview',
        'Expense.view.AddExpenseContainer',
        'Expense.view.Sign'
    ],

    config: {
        fullscreen: false,
        layout: {
            type: 'card'
        },
        items: [
            {
                xtype: 'info'
            },
            {
                xtype: 'overview'
            },
            {
                xtype: 'addexpensecontainer'
            },
            {
                xtype: 'sign'
            }
        ]
    }

});