/*
 * File: app/view/Viewport.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Expense.view.Viewport', {
    extend: 'Ext.Container',
    alias: 'widget.viewport',

    requires: [
        'Expense.view.Menu',
        'Expense.view.Page'
    ],

    config: {
        fullscreen: true,
        height: 765,
        width: 1018,
        layout: {
            type: 'hbox'
        },
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                id: 'toolbar',
                ui: 'light',
                title: 'Expense App',
                layout: {
                    align: 'center',
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'button',
                        docked: 'right',
                        ui: 'back',
                        icon: '',
                        iconCls: 'home',
                        iconMask: true,
                        text: 'Home'
                    }
                ]
            },
            {
                xtype: 'menu'
            },
            {
                xtype: 'page',
                docked: 'right',
                width: 687
            }
        ]
    }

});