/*
 * File: app/store/ExpenseStore.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Expense.store.ExpenseStore', {
    extend: 'Ext.data.Store',
    alias: 'store.expensestore',

    requires: [
        'Expense.model.Expense'
    ],

    config: {
    	autoLoad: true,
        data: [
            {
                type: true,
                doe: '21/09/1990',
                projectCode: '123456',
                amount: 200,
                remarks: 'test',
                currency: '€'
            },
            {
                type: true,
                doe: '20/09/1990',
                projectCode: '123456',
                amount: 300990,
                remarks: 'test',
                currency: '€'
            },
            {
                type: true,
                doe: '19/09/1990',
                projectCode: '123456',
                amount: 5500,
                remarks: 'test',
                currency: '€'
            },
            {
                type: true,
                doe: '18/09/1990',
                projectCode: '123456',
                amount: 350.5,
                remarks: 'test',
                currency: '€'
            },
            {
                type: true,
                doe: '17/09/1990',
                projectCode: '123456',
                amount: 300,
                remarks: 'test',
                currency: '€'
            },
            {
                type: true,
                doe: '16/09/1990',
                projectCode: '123456',
                amount: 300,
                remarks: 'test',
                currency: '€'
            }
        ],
        model: 'Expense.model.Expense',
        storeId: 'expensestore',
        proxy: {
            type: 'ajax',
            url: 'http://localhost:8888/resources/expenseService/getExpenseForms',
            extraParams: {
            	token: '77bd4685-71a8-410a-bfda-4e95534be445'
            },
            actionMethod: {
            	read: 'POST'
            },
            reader: {
                type: 'json'
            }
        },
        sorters: {
            property: 'doe'
        }
    }
});