/*
 * File: app/store/ExpenseStore.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Expense.store.ExpenseStore', {
    extend: 'Ext.data.Store',
    alias: 'store.expensestore',

    requires: [
        'Expense.model.Expense'
    ],

    config: {
        model: 'Expense.model.Expense',
        storeId: 'expensestore',
        proxy: {
            type: 'ajax',
            url: 'http://localhost:8888/resources/expenseService/getExpenseForms',
            extraParams:{
                token: Expense.app.token
            },
            actionMethods: {
                create : 'POST',
                read   : 'POST', // by default GET
                update : 'POST',
                destroy: 'POST'
            },
            reader: {
                type: 'xml',
                rootProperty: 'expenseForms',
                record: 'expenseForm'
            }
        },
        sorters: {
            property: 'doe'
        }
    }
});