/*
 * File: app/model/Employee.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Expense.model.Employee', {
    extend: 'Ext.data.Model',
    alias: 'model.employee',

    config: {
        fields: [
            {
                name: 'firstName',
                type: 'string'
            },
            {
                name: 'lastName',
                type: 'string'
            },
            {
                name: 'employeeNumber',
                type: 'string'
            },
            {
                name: 'unitId',
                type: 'string'
            },
            {
                name: 'email',
                type: 'string'
            },
            {
                name: 'password',
                type: 'string'
            },
            {
                name: 'id',
                type: 'string'
            }
        ],
        validations: [
            {
                type: 'presence',
                field: 'employeeNumber'
            },
            {
                type: 'email',
                field: 'email'
            },
            {
                type: 'presence',
                field: 'unit'
            }
        ]
    }
});