/*
 * File: app/view/DomesticExpense.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Expense.view.DomesticExpense', {
    extend: 'Ext.form.Panel',
    alias: 'widget.domesticexpense',
    id: 'domesticexpense',

    config: {
        scrollable: 'vertical',
        items: [
            {
                xtype: 'fieldset',
                id: 'domesticfield',
                title: '3. Add Expense',
                
                items: [
                    {
                    	  xtype: 'datepickerfield',
                          label: 'Date Of Expense',
                          placeHolder: 'mm/dd/yyyy',
                          value: new Date(),
                          name: 'date'
                    },
                    {
                        xtype: 'textfield',
                        placeHolder: 'Project Code',
                        name: 'projectCode',
                        id: 'projectCodeDomestic'
                    },
                    {
                        xtype: 'radiofield',
                        label: 'Hotel',
                        name: 'expenseType',
                        value:  'Hotel',
                        checked: true
                    },
                    {
                        xtype: 'radiofield',
                        label: 'Restaurant',
                        name: 'expenseType',
                        value:  'Lunch',
                    },
                    {
                        xtype: 'radiofield',
                        id: 'other',
                        label: 'Other (please specify)',
                        name: 'expenseType',
                        value: 'Other'
                    },
                    {
                        xtype: 'radiofield',
                        label: 'Train / Plane tickets',
                        name: 'expenseType',
                        value: 'Ticket'
                    },
                    {
                        xtype: 'radiofield',
                        label: 'Restaurant (Diner)',
                        name: 'expenseType',
                        value:  'Diner'
                    },
                    {
                        xtype: 'textfield',
                        name: 'amount',
                        placeHolder: 'Amount (€)',
                        id: 'amountDomestic'
                    },
                    {
                        xtype: 'textareafield',
                        placeHolder: 'Remarks',
                        name: 'remarks',
                        id: 'remarksDomestic'
                    },
                  //DOMESTIC(1), ABROAD(2);
                    {
                        xtype: 'textfield',
                        name: 'expenseLocation',
                        hidden: true,
                        value: 'Domestic'
                    },
                    {
                        xtype: 'textfield',
                        name: 'currency',
                        hidden: true,
                        value: 'EUR'
                    },
                    {
                        id: 'fileBtnDomestic',
                        xtype: 'fileupload',
                        iconCls: 'download',
                        iconMask: true,
                        ui: 'confirm',
                        text: 'Upload Evidence',
                        width: 229,
                        height: 46,
                        actionUrl: 'getfile.php',
                        returnBase64Data: true
                    },
                    {
                        xtype: 'button',
                        height: 46,
                        ui: 'confirm',
                        width: 229,
                        iconCls: 'add',
                        iconMask: true,
                        text: 'Add',
                        action: 'sendDomesticExpense'
                    }
                ]
            }
        ]
    }

});