/*
 * File: app/view/Menu.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Expense.view.Menu', {
    extend: 'Ext.Panel',
    alias: 'widget.menuPanel',

    config: {
        cls: 'menu-background',
        id: 'menupanel',
        items: [
            {
                xtype: 'list',
                height: '100%',
                id: 'menulist',
                itemId: 'menulist',
                html: '<h1 class=\'x-custom-title\'>New Expense</h1>',
                ui: 'round',
                scrollable: false,
                itemTpl: [
                    '<div>{item}</div>'
                ],
                store: 'menustore'
            }
        ]
    }

});