/*
 * File: app/view/Viewport.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Expense.view.Viewport', {
    extend: 'Ext.Container',
    alias: 'widget.viewport',
    xtype: 'viewport',
    

    requires: [
        'Expense.view.Menu',
        'Expense.view.Page'
    ],

    config: {
        fullscreen: true,
        id: 'viewport',
        layout: {
            pack: 'center',
            type: 'hbox'
        },
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'Expense App',
                items: [
                    {
                        xtype: 'button',
                        align: 'left',
                        id: 'menuButton',
                        iconCls: 'settings',
                        iconMask: true,
                        text: 'Menu',
                        action: 'menu',
                        hidden: true
                    },
                    {
                        xtype: 'button',
                        align: 'right',
                        ui: 'action',
                        iconCls: 'home',
                        iconMask: true,
                        text: 'Home',
                        action: 'home'
                    }
                ]
            },
            {
                xtype: 'menuPanel',
                flex: 1
            },
            {
                xtype: 'page',
                flex: 3
            }
        ]
    }

});